### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [xxv/24hAnalogWidget#11]
Hi, I want to design a new logo for the project completely free...

**Comment by xxv** [comment]
Cool! What did you have in mind?

**Comment by Arslanshn** [comment]
hello I made the logo I hope you like:)
https://drive.google.com/drive/folders/1zvuUL_mbhFluWc3GUgUU2wh91CGsduco?usp=sharing

**Comment by xxv** [comment]
Thanks for the logo. I think I'll be sticking with the one we've already got. Cheers!

**Comment by xxv** [comment]
BTW: Feel free to reach out if you'd like feedback on your design.
